namespace ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.AdvisorValueObjects;

/// <summary>
///     A mitigation recommendation generated by the advisor.
/// </summary>
public record MitigationRecommendation
{
    public MitigationActionType ActionType { get; init; }
    public NutritionInputRecommendation SuggestedInputs { get; init; }
    public TimeWindow RecommendedApplicationWindow { get; init; }
    public AgronomicClimateRiskLevel ClimateRiskLevel { get; init; }
}
