using System;
using ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.AdvisorValueObjects;

namespace ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects;

/// <summary>
///     A weather warning generated by the forecast advisor.
/// </summary>
public record AgronomicWeatherWarning
{
    public WeatherWarningType Type { get; init; }
    public AgronomicClimateRiskLevel Severity { get; init; }
    public DateOnly Date { get; init; }
    public string Message { get; init; }

    public AgronomicWeatherWarning(
        WeatherWarningType type,
        AgronomicClimateRiskLevel severity,
        DateOnly date,
        string message)
    {
        if (string.IsNullOrWhiteSpace(message))
            throw new ArgumentException("Message cannot be null or empty.", nameof(message));

        Type = type;
        Severity = severity;
        Date = date;
        Message = message;
    }
}
