namespace ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects;

/// <summary>
///     Type of weather warning generated by the advisor.
/// </summary>
public enum WeatherWarningType
{
    Frost,
    HeatStress,
    Storm,
    HighWind,
    HeavyRain
}
