// <auto-generated />
using System;
using System.Collections.Generic;
using ArcadiaDevs.Viora.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArcadiaDevs.Viora.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260704081916_AddCoupon")]
    partial class AddCoupon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.AgronomicStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ChillHours")
                        .HasColumnType("double precision")
                        .HasColumnName("chill_hours");

                    b.Property<double>("ChillPortions")
                        .HasColumnType("double precision")
                        .HasColumnName("chill_portions");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("MeasurementDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measurement_date");

                    b.Property<double>("NdviValue")
                        .HasColumnType("double precision")
                        .HasColumnName("ndvi_value");

                    b.Property<long>("PlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("plot_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_agronomic_statistics");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_agronomic_statistics_user_id");

                    b.HasIndex("PlotId", "MeasurementDate")
                        .HasDatabaseName("ix_agronomic_statistics_plot_id_measurement_date");

                    b.ToTable("agronomic_statistics", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.DynamicNutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("GeneratedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_date");

                    b.Property<int>("PlotId")
                        .HasColumnType("integer")
                        .HasColumnName("plot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_dynamic_nutrition_plans");

                    b.ToTable("dynamic_nutrition_plans", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.IoTDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActivationCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("activation_code");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<long>("PlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("plot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_iot_devices");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_iot_devices_plot_id");

                    b.HasIndex("Id", "PlotId")
                        .HasDatabaseName("ix_iot_devices_id_plot_id");

                    b.ToTable("iot_devices", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.MonitoringSummary", b =>
                {
                    b.Property<long>("MonitoringSummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MonitoringSummaryId"));

                    b.Property<decimal>("AccumulatedChillHours")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("accumulated_chill_hours");

                    b.Property<decimal>("AverageNdvi")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("average_ndvi");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GeneralHealthStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("general_health_status");

                    b.Property<DateTimeOffset>("LastSynchronizationAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synchronization_at");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("YieldProjection")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("yield_projection");

                    b.ComplexProperty<Dictionary<string, object>>("MitigationRecommendation", "ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.MonitoringSummary.MitigationRecommendation#MitigationRecommendation", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ActionType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("mitigation_action_type");

                            b1.Property<string>("RecommendedApplicationWindow")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("mitigation_recommended_application_window");

                            b1.Property<string>("SuggestedInputs")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("mitigation_suggested_inputs");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("WeatherSnapshot", "ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.MonitoringSummary.WeatherSnapshot#WeatherSnapshot", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("ClimateRiskLevel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("weather_climate_risk_level");

                            b1.Property<decimal>("CurrentTemperature")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("weather_current_temperature");

                            b1.Property<DateTimeOffset>("LastValidatedReadingAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("weather_last_validated_reading_at");

                            b1.Property<string>("WeatherStatus")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("weather_status");
                        });

                    b.HasKey("MonitoringSummaryId")
                        .HasName("p_k_monitoring_summaries");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_monitoring_summaries_user_id");

                    b.ToTable("monitoring_summaries", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgroMonitoringCenter")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agro_monitoring_center");

                    b.Property<string>("AgroMonitoringPolygonId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agro_monitoring_polygon_id");

                    b.Property<decimal>("AreaSize")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("area_size");

                    b.Property<string>("Campaign")
                        .HasColumnType("text")
                        .HasColumnName("campaign");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CropType")
                        .HasColumnType("text")
                        .HasColumnName("crop_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PlotName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("plot_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variety")
                        .HasColumnType("text")
                        .HasColumnName("variety");

                    b.HasKey("Id")
                        .HasName("p_k_plots");

                    b.ToTable("plots", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Entities.AgroMonitoringPlotIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoundaryFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("boundary_fingerprint");

                    b.Property<DateTimeOffset?>("CaptureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_date");

                    b.Property<double?>("CloudPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("cloud_percentage");

                    b.Property<string>("ExternalPolygonId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_polygon_id");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<double?>("NdviMean")
                        .HasColumnType("double precision")
                        .HasColumnName("ndvi_mean");

                    b.Property<int>("PlotId")
                        .HasColumnType("integer")
                        .HasColumnName("plot_id");

                    b.Property<string>("ProviderImageryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_imagery_id");

                    b.Property<string>("TileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tile_url");

                    b.HasKey("Id")
                        .HasName("p_k_agronomic_agro_monitoring_plot_integrations");

                    b.HasIndex("PlotId")
                        .IsUnique()
                        .HasDatabaseName("i_x_agronomic_agro_monitoring_plot_integrations_plot_id");

                    b.ToTable("agronomic_agro_monitoring_plot_integrations", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Billing.Domain.Model.Aggregates.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("conditions");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer")
                        .HasColumnName("discount_percent");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("p_k_coupons");

                    b.HasIndex("UserId", "Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_coupons_user_id_code");

                    b.ToTable("coupons", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Billing.Domain.Model.Aggregates.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("ExternalPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_payment_id");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_invoices");

                    b.HasIndex("ExternalPaymentId")
                        .IsUnique()
                        .HasDatabaseName("i_x_invoices_external_payment_id");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Billing.Domain.Model.Aggregates.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("brand");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("integer")
                        .HasColumnName("exp_month");

                    b.Property<int>("ExpYear")
                        .HasColumnType("integer")
                        .HasColumnName("exp_year");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("is_default");

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("last4");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_payment_methods");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_payment_methods_user_id");

                    b.ToTable("payment_methods", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Billing.Domain.Model.Aggregates.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("features");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interval");

                    b.Property<int>("IotLimit")
                        .HasColumnType("integer")
                        .HasColumnName("iot_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("PlotLimit")
                        .HasColumnType("integer")
                        .HasColumnName("plot_limit");

                    b.Property<decimal>("PriceAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price_amount");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("tagline");

                    b.HasKey("Id")
                        .HasName("p_k_plans");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("i_x_plans_code");

                    b.ToTable("plans", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Billing.Domain.Model.Aggregates.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_end");

                    b.Property<string>("Interval")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interval");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("plan_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_subscriptions_user_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Iam.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("i_x_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.InterventionExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ApplicationDate")
                        .HasColumnType("date")
                        .HasColumnName("application_date");

                    b.Property<decimal>("AppliedArea")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("applied_area");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("execution_status");

                    b.Property<string>("FieldNote")
                        .HasColumnType("text")
                        .HasColumnName("field_note");

                    b.Property<int>("TreatmentPrescriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_prescription_id");

                    b.HasKey("Id")
                        .HasName("p_k_intervention_executions");

                    b.HasIndex("TreatmentPrescriptionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_intervention_executions_treatment_prescription_id");

                    b.ToTable("intervention_executions", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.InterventionOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InterventionExecutionId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_execution_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_intervention_outcomes");

                    b.HasIndex("InterventionExecutionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_intervention_outcomes_intervention_execution_id");

                    b.ToTable("intervention_outcomes", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.InterventionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long?>("AlertId")
                        .HasColumnType("bigint")
                        .HasColumnName("alert_id");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text")
                        .HasColumnName("decline_reason");

                    b.Property<int>("GrowerId")
                        .HasColumnType("integer")
                        .HasColumnName("grower_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<long>("PlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("plot_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("integer")
                        .HasColumnName("specialist_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_intervention_requests");

                    b.HasIndex("GrowerId")
                        .HasDatabaseName("i_x_intervention_requests_grower_id");

                    b.HasIndex("SpecialistId")
                        .HasDatabaseName("i_x_intervention_requests_specialist_id");

                    b.ToTable("intervention_requests", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.ServiceProposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DurationLabel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duration_label");

                    b.Property<int>("InterventionRequestId")
                        .HasColumnType("integer")
                        .HasColumnName("intervention_request_id");

                    b.Property<string>("ProposalDetails")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proposal_details");

                    b.Property<DateOnly>("ProposedDate")
                        .HasColumnType("date")
                        .HasColumnName("proposed_date");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("ServiceTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_title");

                    b.Property<int>("SpecialistId")
                        .HasColumnType("integer")
                        .HasColumnName("specialist_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_service_proposals");

                    b.HasIndex("InterventionRequestId")
                        .HasDatabaseName("i_x_service_proposals_intervention_request_id");

                    b.ToTable("service_proposals", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("availability");

                    b.Property<int>("CaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("case_count");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_km");

                    b.Property<int>("ProfileUserId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_user_id");

                    b.Property<double>("SuccessRate")
                        .HasColumnType("double precision")
                        .HasColumnName("success_rate");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tags");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("whatsapp");

                    b.HasKey("Id")
                        .HasName("p_k_specialists");

                    b.HasIndex("ProfileUserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_specialists_profile_user_id");

                    b.ToTable("specialists", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.TreatmentPrescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceProposalId")
                        .HasColumnType("integer")
                        .HasColumnName("service_proposal_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_treatment_prescriptions");

                    b.HasIndex("ServiceProposalId")
                        .IsUnique()
                        .HasDatabaseName("i_x_treatment_prescriptions_service_proposal_id");

                    b.ToTable("treatment_prescriptions", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Profile.Domain.Model.Aggregates.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("location");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SpecialtyArea")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("specialty_area");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("i_x_profiles_user_id");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataProviders")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_providers");

                    b.Property<string>("RiskExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_explanation");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sources");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupportingData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supporting_data");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.PestSightingReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AlertConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_confirmed");

                    b.Property<string>("CalculatedRisk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calculated_risk");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Evaluated")
                        .HasColumnType("boolean")
                        .HasColumnName("evaluated");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ObservedSeverity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observed_severity");

                    b.Property<string>("ProbableThreat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("probable_threat");

                    b.Property<string>("RiskZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_pest_sighting_reports");

                    b.ToTable("pest_sighting_reports");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Entities.AlertTimelineRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlertId")
                        .HasColumnType("bigint")
                        .HasColumnName("alert_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("p_k_alert_timeline_records");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("i_x_alert_timeline_records_alert_id");

                    b.ToTable("alert_timeline_records");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Entities.SymptomDictionaryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionEs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_es");

                    b.HasKey("Id")
                        .HasName("p_k_symptom_dictionary_items");

                    b.ToTable("symptom_dictionary_items");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("integer")
                        .HasColumnName("roles_id");

                    b.Property<int>("UsersId")
                        .HasColumnType("integer")
                        .HasColumnName("users_id");

                    b.HasKey("RolesId", "UsersId")
                        .HasName("p_k_user_roles");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("i_x_user_roles_users_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.AgronomicStatistic", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.ChillModelState", "ChillModelState", b1 =>
                        {
                            b1.Property<long>("AgronomicStatisticId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<double>("IntermediateProduct")
                                .HasColumnType("double precision")
                                .HasColumnName("chill_model_intermediate_product");

                            b1.Property<double?>("PreviousHourTemperatureCelsius")
                                .HasColumnType("double precision")
                                .HasColumnName("chill_model_previous_hour_temperature_celsius");

                            b1.Property<double?>("PriorHourTemperatureCelsius")
                                .HasColumnType("double precision")
                                .HasColumnName("chill_model_prior_hour_temperature_celsius");

                            b1.HasKey("AgronomicStatisticId")
                                .HasName("p_k_agronomic_statistics");

                            b1.ToTable("agronomic_statistics");

                            b1.WithOwner()
                                .HasForeignKey("AgronomicStatisticId")
                                .HasConstraintName("f_k_agronomic_statistics_agronomic_statistics_id");
                        });

                    b.Navigation("ChillModelState")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.DynamicNutritionPlan", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.NutritionApplication", "Application", b1 =>
                        {
                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("ApplicationDate")
                                .HasColumnType("date")
                                .HasColumnName("application_date");

                            b1.Property<TimeOnly>("ApplicationTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("application_time");

                            b1.Property<string>("AppliedInputs")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("applied_inputs");

                            b1.Property<string>("DoseConfirmation")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("dose_confirmation");

                            b1.Property<string>("FieldNotes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("field_notes");

                            b1.Property<string>("FieldOperator")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("field_operator");

                            b1.HasKey("DynamicNutritionPlanId")
                                .HasName("p_k_dynamic_nutrition_plans");

                            b1.ToTable("dynamic_nutrition_plans");

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plans_dynamic_nutrition_plans_id");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.NutritionApplicationWindow", "ApplicationWindow", b1 =>
                        {
                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("application_window_end");

                            b1.Property<DateTimeOffset>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("application_window_start");

                            b1.HasKey("DynamicNutritionPlanId")
                                .HasName("p_k_dynamic_nutrition_plans");

                            b1.ToTable("dynamic_nutrition_plans");

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plans_dynamic_nutrition_plans_id");
                        });

                    b.OwnsMany("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.NutritionInputRecommendation", "InputRecommendations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Dosage")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("dosage");

                            b1.Property<string>("DosageUnit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("dosage_unit");

                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("dynamic_nutrition_plan_id");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("purpose");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("status");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("p_k_dynamic_nutrition_plan_inputs");

                            b1.HasIndex("DynamicNutritionPlanId")
                                .HasDatabaseName("i_x_dynamic_nutrition_plan_inputs_dynamic_nutrition_plan_id");

                            b1.ToTable("dynamic_nutrition_plan_inputs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plan_inputs_dynamic_nutrition_plans_dynam~");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.PlanRationale", "Rationale", b1 =>
                        {
                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<double>("NdviValue")
                                .HasColumnType("decimal(4,2)")
                                .HasColumnName("ndvi_value");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("rationale_summary");

                            b1.Property<double>("TemperatureAnomaly")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("temperature_anomaly");

                            b1.Property<string>("TriggeringRiskLevel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("triggering_risk_level");

                            b1.HasKey("DynamicNutritionPlanId")
                                .HasName("p_k_dynamic_nutrition_plans");

                            b1.ToTable("dynamic_nutrition_plans");

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plans_dynamic_nutrition_plans_id");
                        });

                    b.Navigation("Application");

                    b.Navigation("ApplicationWindow")
                        .IsRequired();

                    b.Navigation("InputRecommendations");

                    b.Navigation("Rationale")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.Plot", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.ChillRequirement", "ChillRequirementOverride", b1 =>
                        {
                            b1.Property<int>("PlotId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("chill_requirement_model");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("chill_requirement_source");

                            b1.HasKey("PlotId")
                                .HasName("p_k_plots");

                            b1.ToTable("plots");

                            b1.WithOwner()
                                .HasForeignKey("PlotId")
                                .HasConstraintName("f_k_plots_plots_id");

                            b1.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.ChillPortions", "Portions", b2 =>
                                {
                                    b2.Property<int>("ChillRequirementPlotId")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<double>("Value")
                                        .HasColumnType("decimal(18,6)")
                                        .HasColumnName("chill_requirement_portions");

                                    b2.HasKey("ChillRequirementPlotId")
                                        .HasName("p_k_plots");

                                    b2.ToTable("plots");

                                    b2.WithOwner()
                                        .HasForeignKey("ChillRequirementPlotId")
                                        .HasConstraintName("f_k_plots_plots_id");
                                });

                            b1.Navigation("Portions")
                                .IsRequired();
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.PolygonCoordinates", "PolygonCoordinates", b1 =>
                        {
                            b1.Property<int>("PlotId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Points")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("polygon_coordinates");

                            b1.HasKey("PlotId")
                                .HasName("p_k_plots");

                            b1.ToTable("plots");

                            b1.WithOwner()
                                .HasForeignKey("PlotId")
                                .HasConstraintName("f_k_plots_plots_id");
                        });

                    b.Navigation("ChillRequirementOverride");

                    b.Navigation("PolygonCoordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.InterventionOutcome", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.ValueObjects.ImpactReport", "ImpactReport", b1 =>
                        {
                            b1.Property<int>("InterventionOutcomeId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("GracePeriod")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("grace_period");

                            b1.Property<string>("ImpactLevel")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("impact_level");

                            b1.Property<string>("ObservedResult")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("observed_result");

                            b1.Property<string>("ProducerAssessment")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("producer_assessment");

                            b1.HasKey("InterventionOutcomeId")
                                .HasName("p_k_intervention_outcomes");

                            b1.ToTable("intervention_outcomes");

                            b1.WithOwner()
                                .HasForeignKey("InterventionOutcomeId")
                                .HasConstraintName("f_k_intervention_outcomes_intervention_outcomes_id");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.ValueObjects.ServiceEvaluation", "ServiceEvaluation", b1 =>
                        {
                            b1.Property<int>("InterventionOutcomeId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<bool>("HireAgain")
                                .HasColumnType("boolean")
                                .HasColumnName("hire_again");

                            b1.Property<string>("PrivateFeedback")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("private_feedback");

                            b1.Property<string>("ServiceResult")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("service_result");

                            b1.HasKey("InterventionOutcomeId")
                                .HasName("p_k_intervention_outcomes");

                            b1.ToTable("intervention_outcomes");

                            b1.WithOwner()
                                .HasForeignKey("InterventionOutcomeId")
                                .HasConstraintName("f_k_intervention_outcomes_intervention_outcomes_id");
                        });

                    b.Navigation("ImpactReport")
                        .IsRequired();

                    b.Navigation("ServiceEvaluation");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.ServiceProposal", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.ValueObjects.CostEstimate", "CostEstimate", b1 =>
                        {
                            b1.Property<int>("ServiceProposalId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("cost_estimate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("cost_estimate_currency");

                            b1.HasKey("ServiceProposalId")
                                .HasName("p_k_service_proposals");

                            b1.ToTable("service_proposals");

                            b1.WithOwner()
                                .HasForeignKey("ServiceProposalId")
                                .HasConstraintName("f_k_service_proposals_service_proposals_id");
                        });

                    b.Navigation("CostEstimate")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.Aggregates.TreatmentPrescription", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.ValueObjects.AgrochemicalPrescription", "AgrochemicalPrescription", b1 =>
                        {
                            b1.Property<int>("TreatmentPrescriptionId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("AgronomistRecommendations")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("agronomist_recommendations");

                            b1.Property<string>("ApplicationMethod")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("application_method");

                            b1.Property<string>("PreHarvestInterval")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pre_harvest_interval");

                            b1.Property<string>("Products")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("products");

                            b1.Property<string>("RequiredPPE")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("required_ppe");

                            b1.Property<string>("SprayVolume")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("spray_volume");

                            b1.HasKey("TreatmentPrescriptionId")
                                .HasName("p_k_treatment_prescriptions");

                            b1.ToTable("treatment_prescriptions");

                            b1.WithOwner()
                                .HasForeignKey("TreatmentPrescriptionId")
                                .HasConstraintName("f_k_treatment_prescriptions_treatment_prescriptions_id");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Intervention.Domain.Model.ValueObjects.FieldInspectionRecord", "FieldInspectionRecord", b1 =>
                        {
                            b1.Property<int>("TreatmentPrescriptionId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("FindingType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("finding_type");

                            b1.Property<string>("IncidenceLevel")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("incidence_level");

                            b1.Property<DateOnly>("RecordDate")
                                .HasColumnType("date")
                                .HasColumnName("record_date");

                            b1.Property<string>("TechnicalDescription")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("technical_description");

                            b1.HasKey("TreatmentPrescriptionId")
                                .HasName("p_k_treatment_prescriptions");

                            b1.ToTable("treatment_prescriptions");

                            b1.WithOwner()
                                .HasForeignKey("TreatmentPrescriptionId")
                                .HasConstraintName("f_k_treatment_prescriptions_treatment_prescriptions_id");
                        });

                    b.Navigation("AgrochemicalPrescription");

                    b.Navigation("FieldInspectionRecord");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.ValueObjects.PlotId", "PlotId", b1 =>
                        {
                            b1.Property<long>("AlertId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("plot_id");

                            b1.HasKey("AlertId")
                                .HasName("p_k_alerts");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId")
                                .HasConstraintName("f_k_alerts_alerts_id");
                        });

                    b.Navigation("PlotId")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.PestSightingReport", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.ValueObjects.PlotId", "PlotId", b1 =>
                        {
                            b1.Property<long>("PestSightingReportId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("plot_id");

                            b1.HasKey("PestSightingReportId")
                                .HasName("p_k_pest_sighting_reports");

                            b1.ToTable("pest_sighting_reports");

                            b1.WithOwner()
                                .HasForeignKey("PestSightingReportId")
                                .HasConstraintName("f_k_pest_sighting_reports_pest_sighting_reports_id");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.ValueObjects.ReporterUserId", "ReporterUserId", b1 =>
                        {
                            b1.Property<long>("PestSightingReportId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("reporter_user_id");

                            b1.HasKey("PestSightingReportId")
                                .HasName("p_k_pest_sighting_reports");

                            b1.ToTable("pest_sighting_reports");

                            b1.WithOwner()
                                .HasForeignKey("PestSightingReportId")
                                .HasConstraintName("f_k_pest_sighting_reports_pest_sighting_reports_id");
                        });

                    b.Navigation("PlotId")
                        .IsRequired();

                    b.Navigation("ReporterUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Entities.AlertTimelineRecord", b =>
                {
                    b.HasOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", null)
                        .WithMany("Timeline")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alert_timeline_records_alerts_alert_id");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("ArcadiaDevs.Viora.Platform.Iam.Domain.Model.Aggregates.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_roles_roles_roles_id");

                    b.HasOne("ArcadiaDevs.Viora.Platform.Iam.Domain.Model.Aggregates.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_user_roles_users_users_id");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
