// <auto-generated />
using System;
using ArcadiaDevs.Viora.Platform.Shared.Infrastructure.Persistence.EntityFrameworkCore.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArcadiaDevs.Viora.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.DynamicNutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("GeneratedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_date");

                    b.Property<int>("PlotId")
                        .HasColumnType("integer")
                        .HasColumnName("plot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_dynamic_nutrition_plans");

                    b.ToTable("dynamic_nutrition_plans", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.IoTDevice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_name");

                    b.Property<long>("PlotId")
                        .HasColumnType("bigint")
                        .HasColumnName("plot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_iot_devices");

                    b.HasIndex("PlotId")
                        .HasDatabaseName("ix_iot_devices_plot_id");

                    b.HasIndex("Id", "PlotId")
                        .HasDatabaseName("ix_iot_devices_id_plot_id");

                    b.ToTable("iot_devices", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.Plot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgroMonitoringCenter")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agro_monitoring_center");

                    b.Property<string>("AgroMonitoringPolygonId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("agro_monitoring_polygon_id");

                    b.Property<decimal>("AreaSize")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("area_size");

                    b.Property<string>("Campaign")
                        .HasColumnType("text")
                        .HasColumnName("campaign");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CropType")
                        .HasColumnType("text")
                        .HasColumnName("crop_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("PlotName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("plot_name");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Variety")
                        .HasColumnType("text")
                        .HasColumnName("variety");

                    b.HasKey("Id")
                        .HasName("p_k_plots");

                    b.ToTable("plots", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Entities.AgroMonitoringPlotIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoundaryFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("boundary_fingerprint");

                    b.Property<DateTimeOffset?>("CaptureDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capture_date");

                    b.Property<double?>("CloudPercentage")
                        .HasColumnType("double precision")
                        .HasColumnName("cloud_percentage");

                    b.Property<string>("ExternalPolygonId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_polygon_id");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<double?>("NdviMean")
                        .HasColumnType("double precision")
                        .HasColumnName("ndvi_mean");

                    b.Property<int>("PlotId")
                        .HasColumnType("integer")
                        .HasColumnName("plot_id");

                    b.Property<string>("ProviderImageryId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_imagery_id");

                    b.Property<string>("TileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("tile_url");

                    b.HasKey("Id")
                        .HasName("p_k_agronomic_agro_monitoring_plot_integrations");

                    b.HasIndex("PlotId")
                        .IsUnique()
                        .HasDatabaseName("i_x_agronomic_agro_monitoring_plot_integrations_plot_id");

                    b.ToTable("agronomic_agro_monitoring_plot_integrations", (string)null);
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataProviders")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_providers");

                    b.Property<string>("RiskExplanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_explanation");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sources");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SupportingData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supporting_data");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_alerts");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.PestSightingReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AlertConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("alert_confirmed");

                    b.Property<string>("CalculatedRisk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calculated_risk");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Evaluated")
                        .HasColumnType("boolean")
                        .HasColumnName("evaluated");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("ObservedSeverity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observed_severity");

                    b.Property<string>("ProbableThreat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("probable_threat");

                    b.Property<string>("RiskZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("risk_zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_pest_sighting_reports");

                    b.ToTable("pest_sighting_reports");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Entities.AlertTimelineRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AlertId")
                        .HasColumnType("bigint")
                        .HasColumnName("alert_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("p_k_alert_timeline_records");

                    b.HasIndex("AlertId")
                        .HasDatabaseName("i_x_alert_timeline_records_alert_id");

                    b.ToTable("alert_timeline_records");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Entities.SymptomDictionaryItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionEs")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description_es");

                    b.HasKey("Id")
                        .HasName("p_k_symptom_dictionary_items");

                    b.ToTable("symptom_dictionary_items");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.DynamicNutritionPlan", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.NutritionApplication", "Application", b1 =>
                        {
                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("ApplicationDate")
                                .HasColumnType("date")
                                .HasColumnName("application_date");

                            b1.Property<TimeOnly>("ApplicationTime")
                                .HasColumnType("time without time zone")
                                .HasColumnName("application_time");

                            b1.Property<string>("AppliedInputs")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("applied_inputs");

                            b1.Property<string>("DoseConfirmation")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("dose_confirmation");

                            b1.Property<string>("FieldNotes")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("field_notes");

                            b1.Property<string>("FieldOperator")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("field_operator");

                            b1.HasKey("DynamicNutritionPlanId")
                                .HasName("p_k_dynamic_nutrition_plans");

                            b1.ToTable("dynamic_nutrition_plans");

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plans_dynamic_nutrition_plans_id");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.NutritionApplicationWindow", "ApplicationWindow", b1 =>
                        {
                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset>("EndDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("application_window_end");

                            b1.Property<DateTimeOffset>("StartDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("application_window_start");

                            b1.HasKey("DynamicNutritionPlanId")
                                .HasName("p_k_dynamic_nutrition_plans");

                            b1.ToTable("dynamic_nutrition_plans");

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plans_dynamic_nutrition_plans_id");
                        });

                    b.OwnsMany("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.NutritionInputRecommendation", "InputRecommendations", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<double>("Dosage")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("dosage");

                            b1.Property<string>("DosageUnit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("dosage_unit");

                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("dynamic_nutrition_plan_id");

                            b1.Property<string>("Purpose")
                                .IsRequired()
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("purpose");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("status");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("value");

                            b1.HasKey("Id")
                                .HasName("p_k_dynamic_nutrition_plan_inputs");

                            b1.HasIndex("DynamicNutritionPlanId")
                                .HasDatabaseName("i_x_dynamic_nutrition_plan_inputs_dynamic_nutrition_plan_id");

                            b1.ToTable("dynamic_nutrition_plan_inputs", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plan_inputs_dynamic_nutrition_plans_dynam~");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.PlanRationale", "Rationale", b1 =>
                        {
                            b1.Property<int>("DynamicNutritionPlanId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<double>("NdviValue")
                                .HasColumnType("decimal(4,2)")
                                .HasColumnName("ndvi_value");

                            b1.Property<string>("Summary")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("rationale_summary");

                            b1.Property<double>("TemperatureAnomaly")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("temperature_anomaly");

                            b1.Property<string>("TriggeringRiskLevel")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("triggering_risk_level");

                            b1.HasKey("DynamicNutritionPlanId")
                                .HasName("p_k_dynamic_nutrition_plans");

                            b1.ToTable("dynamic_nutrition_plans");

                            b1.WithOwner()
                                .HasForeignKey("DynamicNutritionPlanId")
                                .HasConstraintName("f_k_dynamic_nutrition_plans_dynamic_nutrition_plans_id");
                        });

                    b.Navigation("Application");

                    b.Navigation("ApplicationWindow")
                        .IsRequired();

                    b.Navigation("InputRecommendations");

                    b.Navigation("Rationale")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.Aggregates.Plot", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.ChillRequirement", "ChillRequirementOverride", b1 =>
                        {
                            b1.Property<int>("PlotId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("chill_requirement_model");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("chill_requirement_source");

                            b1.HasKey("PlotId")
                                .HasName("p_k_plots");

                            b1.ToTable("plots");

                            b1.WithOwner()
                                .HasForeignKey("PlotId")
                                .HasConstraintName("f_k_plots_plots_id");

                            b1.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.ChillPortions", "Portions", b2 =>
                                {
                                    b2.Property<int>("ChillRequirementPlotId")
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    b2.Property<double>("Value")
                                        .HasColumnType("decimal(18,6)")
                                        .HasColumnName("chill_requirement_portions");

                                    b2.HasKey("ChillRequirementPlotId")
                                        .HasName("p_k_plots");

                                    b2.ToTable("plots");

                                    b2.WithOwner()
                                        .HasForeignKey("ChillRequirementPlotId")
                                        .HasConstraintName("f_k_plots_plots_id");
                                });

                            b1.Navigation("Portions")
                                .IsRequired();
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Agronomic.Domain.Model.ValueObjects.PolygonCoordinates", "PolygonCoordinates", b1 =>
                        {
                            b1.Property<int>("PlotId")
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            b1.Property<string>("Points")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("polygon_coordinates");

                            b1.HasKey("PlotId")
                                .HasName("p_k_plots");

                            b1.ToTable("plots");

                            b1.WithOwner()
                                .HasForeignKey("PlotId")
                                .HasConstraintName("f_k_plots_plots_id");
                        });

                    b.Navigation("ChillRequirementOverride");

                    b.Navigation("PolygonCoordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.ValueObjects.PlotId", "PlotId", b1 =>
                        {
                            b1.Property<long>("AlertId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("plot_id");

                            b1.HasKey("AlertId")
                                .HasName("p_k_alerts");

                            b1.ToTable("alerts");

                            b1.WithOwner()
                                .HasForeignKey("AlertId")
                                .HasConstraintName("f_k_alerts_alerts_id");
                        });

                    b.Navigation("PlotId")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.PestSightingReport", b =>
                {
                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.ValueObjects.PlotId", "PlotId", b1 =>
                        {
                            b1.Property<long>("PestSightingReportId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("plot_id");

                            b1.HasKey("PestSightingReportId")
                                .HasName("p_k_pest_sighting_reports");

                            b1.ToTable("pest_sighting_reports");

                            b1.WithOwner()
                                .HasForeignKey("PestSightingReportId")
                                .HasConstraintName("f_k_pest_sighting_reports_pest_sighting_reports_id");
                        });

                    b.OwnsOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.ValueObjects.ReporterUserId", "ReporterUserId", b1 =>
                        {
                            b1.Property<long>("PestSightingReportId")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<long>("Value")
                                .HasColumnType("bigint")
                                .HasColumnName("reporter_user_id");

                            b1.HasKey("PestSightingReportId")
                                .HasName("p_k_pest_sighting_reports");

                            b1.ToTable("pest_sighting_reports");

                            b1.WithOwner()
                                .HasForeignKey("PestSightingReportId")
                                .HasConstraintName("f_k_pest_sighting_reports_pest_sighting_reports_id");
                        });

                    b.Navigation("PlotId")
                        .IsRequired();

                    b.Navigation("ReporterUserId")
                        .IsRequired();
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Entities.AlertTimelineRecord", b =>
                {
                    b.HasOne("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", null)
                        .WithMany("Timeline")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alert_timeline_records_alerts_alert_id");
                });

            modelBuilder.Entity("ArcadiaDevs.Viora.Platform.Surveillance.Domain.Model.Aggregates.Alert", b =>
                {
                    b.Navigation("Timeline");
                });
#pragma warning restore 612, 618
        }
    }
}
